library(tidyverse)
library(readr)
library(skimr)

daily_activity <- read_csv('dailyActivity_merged.csv')
sleep_day <- read_csv('sleepDay_merged.csv')
weight_log_info <- read_csv('weightLogInfo_merged.csv')
min_met_narrow <- read_csv('minuteMETsNarrow_merged.csv')
# daily_calories <- read_csv('dailyCalories_merged.csv')
# daily_intensities <- read_csv('dailyIntensities_merged.csv')
# daily_steps <- read_csv('dailySteps_merged.csv')
# heartrate_sec <- read_csv('heartrate_seconds_merged.csv')
# hourly_cal <-read_csv('hourlyCalories_merged.csv')
# hourly_intensities <- read_csv('hourlyIntensities_merged.csv')
# hourly_steps <- read_csv('hourlySteps_merged.csv')
# min_cal_narrow <- read_csv('minuteCaloriesNarrow_merged.csv')
# min_cal_wide <- read_csv('minuteCaloriesWide_merged.csv')
# min_intense_narrow <- read_csv('minuteIntensitiesNarrow_merged.csv')
# min_intense_wide <- read_csv('minuteIntensitiesWide_merged.csv')
# min_sleep <- read_csv('minuteSleep_merged.csv')
# min_steps_narrow <- read_csv('minuteStepsNarrow_merged.csv')
# min_steps_wide <- read_csv('minuteStepsWide_merged.csv')
head(daily_activity)
summary(daily_activity)
str(daily_activity)
skim_without_charts(daily_activity)
glimpse(daily_activity)
colnames(daily_activity)
skim_without_charts(daily_calories)
skim_without_charts(daily_activity$Id)
skim_without_charts(daily_activity$Calories)
unique(daily_activity$ActivityDate)
